name: CI

on: [member]

jobs:
  libtest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go test lib
      uses: ./.github/actions/go-test/
      with:
        dir: ./lib/...

  libfmt:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go fmt lib
      uses: ./.github/actions/go-fmt/
      with:
        dir: ./lib/...

  totest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go test Traffic Ops
      uses: ./.github/actions/go-test
      with:
        dir: ./traffic_ops/traffic_ops_golang/...

  tmtest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go test Traffic Monitor
      uses: ./.github/actions/go-test
      with:
        dir: ./traffic_monitor/...

  tstest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go test Traffic Stats
      uses: ./.github/actions/go-test
      with:
        dir: ./traffic_stats/...

  grovetest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go test Grove
      uses: ./.github/actions/go-test
      with:
        dir: ./grove/...

  atscfgtest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go test ATSTCCfg
      uses: ./.github/actions/go-test
      with:
        dir: ./traffic_ops/ort/atstccfg/...
