name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go test lib
      uses: ./.github/actions/go-test/
      with:
        test-dir: ./lib/...
