name: CI

on: [push]

jobs:
  libtest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go test lib
      uses: ./.github/actions/go-test/
      with:
        dir: ./lib/...

  totest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Go test Traffic Ops
      uses: ./.github/actions/go-test
      with:
        dir: ./traffic_ops/traffic_ops_golang/...
